name: build and test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo build --release
        run: cargo build --release
      - name: cargo test
        run: cargo test --all-targets
